### ISSUE TITLE
Update artifact coordinates for R2DBC Postgres driver

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-bom#44]
With the migration from the R2DBC org to the Postgres org, `r2dbc-postgres` changed its groupId from `io.r2dbc` to `org.postgresql`.

**Comment by tisonkun** [comment]
Hi @mp911de! In https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/319 I notice that when generate a new spring boot application from the starter it still produces:

```groovy
    runtimeOnly 'io.r2dbc:r2dbc-postgresql'
```

as the dependency and thus failed since GAV has changed. Do you know whether this issue should be resolved? (Modify the starter generating logic, I think.)

**Comment by mp911de** [comment]
That's something to be addressed by https://github.com/spring-io/start.spring.io

**Comment by wilkinsona** [comment]
@tisonkun I have opened https://github.com/spring-io/start.spring.io/issues/881.
